### ISSUE TITLE
Google Colab Doesn't work

### ISSUE THREAD

**Issue by ruoshiliu** [stevewongv/SSIS#4]
Your google colab doesn't work. Please look at the following error message when running 
`!python setup.py build develop`
![image](https://user-images.githubusercontent.com/25470644/170800281-7229822f-34c6-4a83-81c7-ad7d84dbf5ac.png)

**Comment by stevewongv** [comment]
Thanks for reporting this. This is because the latest version of PyTorch removes the THC.h file. The simplest workaround is installing previous version of PyTorch like 1.8.1.

**Comment by stevewongv** [comment]
I will update the specific files based on https://github.com/aim-uofa/AdelaiDet/pull/518

**Comment by phongnhhn92** [comment]
Hi @stevewongv, is there any update for this ?

**Comment by stevewongv** [comment]
I just fixed this problem in the latest commit.

**Comment by usama-axcelerate** [comment]
I still see this error
![image](https://user-images.githubusercontent.com/132329724/236434985-d18bb17f-e110-4b0f-a2d3-d2ae12e11ce7.png)
